name: CI-Polaris
on:
  workflow_call:
jobs:
  polaris-scan:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Polaris PR Scan
        if: ${{ github.event_name == ‘pull_request’ }}
        uses: synopsys-sig/synopsys-action@v1.5.0
        with:
          polaris_serverUrl: ${{ secrets.POLARIS_SERVER_URL }}
          polaris_accessToken: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          polaris_application_name: “Typescript”
          polaris_project_name: “Test_info”
          polaris_assessment_types: “SAST”
